include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false # We need print for debugging or displaying output
    use_build_context_synchronously: false # For simplicity in error handling
